#%RAML 1.0
title: FHIR R4 US Core Patient API
version: v1
description: FHIR R4 US Core Patient API

mediaType:
  - application/fhir+xml
  - application/fhir+json
protocols:
  - https


uses:
  resourceTypes: /exchange_modules/org.mule.examples/fhir-r4-resource-types-library/1.0.3/fhir-r4-resource-types-library.raml
  patient: /exchange_modules/org.mule.examples/fhir-r4-us-core-patient-library/1.0.1/fhir-r4-us-core-patient-library.raml


/Patient:
  type: {resourceTypes.fhirResourceType: {
      postExample : !include /examples/requests/post_resource.json,
      getExample  : !include /examples/responses/get_resource.json,
      bundleName : patient.PatientBundle,
      resourceName: patient.Patient
    }
  }
  
  /{id}:
    type: {resourceTypes.fhirResource: {
        getSingleExample: !include /examples/responses/get_resource_id.json,
        putExample: !include /examples/requests/put_resource_id.json,
        resourceName: patient.Patient
      }
    }
    